development:
  adapter: postgresql
  encoding: unicode
  database: wastenot_development 
  pool: 5
  username: wastenot
  password: wastenot

test:
  adapter: postgresql
  encoding: unicode
  database: wastenot_test 
  pool: 5
  username: wastenot
  password: wastenot
