development:
  adapter: mysql2
  encoding: utf8
  database: wastenot_development 
  pool: 5
  username: wastenot
  password: wastenot

test:
  adapter: mysql2
  encoding: utf8
  database: wastenot_test 
  pool: 5
  username: wastenot
  password: wastenot
